### ISSUE TITLE
ActivityMainBinding.inflate(layoutInflater)

### ISSUE THREAD

**Issue by ihavetime110** [googlesamples/android-databinding#4]
//The layout for this activity is a Data Binding layout so it needs to be inflated using DataBindingUtil.
 //           val binding: ActivityMainBinding = DataBindingUtil.setContentView(
 //                this, R.layout.activity_main)

        // i replace it with follows, but  when i click the button ,it do not work.
        // why? what i need to do ?
        setContentView(R.layout.activity_main)
        val binding: ActivityMainBinding = ActivityMainBinding.inflate(layoutInflater)!!

        // The returned binding has references to all the Views with an ID.
        binding.observableFieldsActivityButton.setOnClickListener {
            startActivity(Intent(this, ObservableFieldActivity::class.java))
        }
        binding.viewmodelActivityButton.setOnClickListener {
            startActivity(Intent(this, ViewModelActivity::class.java))
        }

**Comment by ihavetime110** [comment]
They all used the  DataBindindUtil.bind(null,view,layout) in the later, but one has no work?

**Comment by JoseAlcerreca** [comment]
It uses ActivityMainBinding to inflate, which is another way to do it.
