### ISSUE TITLE
This sample project why not have java version？

### ISSUE THREAD

**Issue by artshell** [googlesamples/android-databinding#9]
fuck kotlin.....

**Comment by LouisCAD** [comment]
@artshell 
1. No such words are tolerated
2. If you didn't [try.kotl.in](https://try.kotl.in), then you should now. That's a small investment for big rewards over Java.

**Comment by LouisCAD** [comment]
@artshell What you think may be different from the reality.
Also, rust does not work in the JVM, while Kotlin does wonderfully.
Open your mind, try Kotlin, you'll see it is very well designed, and is a much better fit for Android than plain Java 6.
On my side, after ~3 years of Java, I tried Kotlin on a new test project. 10 days later, I wrote production code with it. It was about 2 years ago, and I'd never go back.
Kotlin is arguably easy to learn for Java developers, you can get started in less than a week.

**Comment by artshell** [comment]
@LouisCAD thanks
